title: Alex Mollard
email: alexmollard@protonmail.com
baseurl: ""
url: "https://alexmollard.github.io/"
twitter_username: mollard13
github_username:  AlexMollard

# Build settings
theme: just-the-docs
color_scheme: dark
plugins:
  - jekyll-feed